### ISSUE TITLE
Colect Statistics

### ISSUE THREAD

**Issue by andydmh** [Andy-Daniela/Leaves-Classifier#24]
Statistics: Accuracy, Precision, Sensitivity .... 

Some Ideas: 

1. Divide labeled data into training and testing and see how well the classifier performs on testing set
2. Bring new Images from Google and use them to test after training with the entire labeled dataset.

**Comment by dflorit** [comment]
Build a class Statistics inside Data.py that receives the data and builds the confusion matrix and all statistics out of it
